org: deepakrawat1
app: rsys-serverless-example
service: rsys-sample
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /get
          method: get
